# Generated by Django 4.1 on 2022-08-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='disease',
            field=models.ManyToManyField(related_name='user', to='home.disease'),
        ),
    ]
