# Generated by Django 4.1 on 2022-08-11 15:27

from django.db import migrations
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_user_username_user_disease'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', home.models.UserManager()),
            ],
        ),
    ]
